version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=91.218.66.12;Port=4462;Database=postgres;Username=postgres;Password=FeK2olA9hIFHQiaeip3c2uHWm1YTNerTYCkKM3sptkFayUNxN7nvVqK7d2rqmTdn"
      Redis__Configuration: "redis:6379,abortConnect=false"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - server

volumes:
  postgres-data:
